# Generated by Django 5.0.2 on 2024-02-16 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_lesson_course'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.DateTimeField(verbose_name='Дата платежа')),
                ('payment_amount', models.IntegerField(max_length=5, verbose_name='сумма платежа')),
                ('payment_method', models.CharField(choices=[('Наличные', 'Наличные'), ('Перевод', 'Перевод')], max_length=20, verbose_name='способ оплаты')),
                ('paid_course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='оплаченный курс')),
                ('paid_lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materials.lesson', verbose_name='отдельно оплаченный урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
        ),
    ]
