# Generated by Django 5.0.2 on 2024-03-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_payments_payment_id_payments_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_payment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата платежа'),
        ),
    ]
