# Generated by Django 5.0.2 on 2024-02-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status_subscrip',
            field=models.BooleanField(default=False, verbose_name='статус подписки'),
        ),
    ]
