# Generated by Django 5.0.2 on 2024-03-01 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='цена'),
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='сумма цены')),
                ('payment_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка для оплаты')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='идентификатор платежа')),
                ('name', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='name_of_product')),
            ],
            options={
                'verbose_name': 'оплата курса',
                'verbose_name_plural': 'оплата курсов',
            },
        ),
    ]
