# Generated by Django 5.0.2 on 2024-03-02 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_course_price_coursepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='name_of_product'),
        ),
    ]
