# Generated by Django 5.0.2 on 2024-03-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_alter_coursepayment_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePayment',
        ),
    ]
