# Generated by Django 5.0.2 on 2024-03-03 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_delete_coursepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_subscription', to=settings.AUTH_USER_MODEL, verbose_name='подписки'),
        ),
    ]
