# Generated by Django 5.0.2 on 2024-03-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_alter_course_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subscriptions',
        ),
    ]
